config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  root "galleries#index"

  resources :users, only: [:new, :create, :index, :show]

  resources :comments, only: [:create]

  resources :galleries do
    resources :images, only: [:show, :new, :create, :edit, :update]
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy, :edit, :update]
  end

  resources :groups, only: [:index, :new, :create, :show] do
    resources :group_memberships, only: [:create, :destroy]
  end

  resources :tags, only: [:index, :create, :show]
   
 # get "/" => "galleries#index"
 # get "/galleries/new" => "galleries#new"
 # post "/galleries" => "galleries#create"
 # get "/galleries/:id" => "galleries#show"
 # get "/galleries/:id/edit" => "galleries#edit"
 # patch "/galleries/:id" => "galleries#update"
 # delete "/galleries/:id" => "galleries#destroy"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships
  has_many :members, through: :group_memberships

  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

    def show
      @group = Group.find(params[:id])
      @members = @group.members
    end
    
    private

    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/views/groups/index.html.erb
<%= link_to "Create Group", new_group_path %>


<ul>
  <% @groups.each do |group| %>
    <li>
    <%= link_to group.name, group %>  <%if group.members.include? current_user %><%= button_to "--Leave Group--", group_group_membership_path(group, current_user.membership_for(group)), method: :delete %>
    <% else %>
      <%= button_to "Join Group", group_group_memberships_path(group) %>
    <% end %>
    </li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<%= render "error_messages", target: @group %>

<%= form_for @group do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/groups/show.html.erb
<h1>Welcome to the <%= @group.name %> Gallery</h1>

<h2><%= @group.description %></h2>

<h4>Group Members:</h4>

<ul>
  <% @members.each do |member| %>
    <li><%= member.email %></li>
  <% end %>
</ul>