config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  root "galleries#index"

  resources :users, only: [:new, :create, :index, :show]

  resources :comments, only: [:create]

  resources :galleries do
    resources :images, only: [:show, :new, :create, :edit, :update]
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy, :edit, :update]
  end

  resources :groups, only: [:index, :new, :create, :show] do
    resources :group_memberships, only: [:create, :destroy]
  end

  resources :tags, only: [:index, :create, :show]
   
 # get "/" => "galleries#index"
 # get "/galleries/new" => "galleries#new"
 # post "/galleries" => "galleries#create"
 # get "/galleries/:id" => "galleries#show"
 # get "/galleries/:id/edit" => "galleries#edit"
 # patch "/galleries/:id" => "galleries#update"
 # delete "/galleries/:id" => "galleries#destroy"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images
  belongs_to :user
  

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :require_login

  def index
    @galleries = Gallery.all 
    render :index
  end

  def new
    @gallery = current_user.galleries.new
    render :new
  end

  def create 
    @gallery = current_user.galleries.new(gallery_params)

    if @gallery.save
      redirect_to gallery_path(@gallery)
    else
      render :new
    end
  end

  def show
    @gallery = Gallery.find(params[:id]) 
  end

  def edit
    @gallery = load_gallery_from_url
  end

  def update
    @gallery = load_gallery_from_url

    if @gallery.update(gallery_params)
      redirect_to gallery_path(@gallery)
    else
      render :edit
    end
  end


  def destroy 
    gallery = Gallery.find(params[:id])
    gallery.destroy

    redirect_to root_path
  end

  def gallery_params
    params.require(:gallery).permit(:name, :description)
  end

  private

  def load_gallery_from_url
    Gallery.find(params[:id])
  end
end

app/views/galleries/_form.html.erb
<%= render "error_messages", target: gallery %>

<%= form_for gallery do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h2>You are editing <%= @gallery.name %></h2>

<%= link_to "Add Image", new_gallery_image_path(@gallery) %>

<%= render "form", gallery: @gallery %>

app/views/galleries/index.html.erb
<h1>Pixtr says HI</h1>

<a href="/galleries/new">Make a new gallery</a>

<ul>
  <% @galleries.each do |gallery| %>
    <li>
  <a href="/galleries/<%= gallery.id %>">

    <%= link_to gallery.name, gallery %> - <%= gallery.description %>
    <%= link_to "Edit", edit_gallery_path(gallery) %>

    <%= form_for gallery, method: :delete do |form| %>
      <%= form.submit "Delete" %>
    <% end %>
    </li>
  <% end %>
  </ul>

app/views/galleries/new.html.erb
<h2>Create a new gallery</h2>

<%= render "form", gallery: @gallery %>

app/views/galleries/show.html.erb
<h1>This is a page for <%= @gallery.name %></h2>

<ul>
  <% @gallery.images.each do |image| %>
    <li><%= image_tag image.url %>
      <%= link_to image.name, gallery_image_path(@gallery, image) %>
        <% end %>
    </li>
</ul>
<a href="/galleries/<%= @gallery.id %>/edit">Edit</a>