config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  root "galleries#index"

  resources :users, only: [:new, :create, :index, :show]

  resources :comments, only: [:create]

  resources :galleries do
    resources :images, only: [:show, :new, :create, :edit, :update]
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy, :edit, :update]
  end

  resources :groups, only: [:index, :new, :create, :show] do
    resources :group_memberships, only: [:create, :destroy]
  end

  resources :tags, only: [:index, :create, :show]
   
 # get "/" => "galleries#index"
 # get "/galleries/new" => "galleries#new"
 # post "/galleries" => "galleries#create"
 # get "/galleries/:id" => "galleries#show"
 # get "/galleries/:id/edit" => "galleries#edit"
 # patch "/galleries/:id" => "galleries#update"
 # delete "/galleries/:id" => "galleries#destroy"
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  has_many :comments
  has_many :likes
  has_many :groupings
  has_many :groups, through: :groupings
  has_many :image_tags
  has_many :tags, through: :image_tags

  validates :name, presence: true
  validates :url, presence: true

  def tag_words
    tags.pluck(:name).join(', ')
  end

  def tag_words=(tag_string)
    words = tag_string.split(', ')
    ids = words.map{ |word| Tag.find_or_create_by(name: word).id}
    self.tag_ids = ids
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show 
    @gallery = load_gallery_from_url
    @image = @gallery.images.find(params[:id])
    @comment = Comment.new
    @comments = @image.comments.recent 
    @image_like_count = @image.likes.count
    @image_likes = @image.likes
    @available_tags = Tag.all
    @number_of_tags = Tag.count
  end

  def new
    @gallery = load_gallery_from_url
    @image = @gallery.images.new
  end

  def create
    @gallery = load_gallery_from_url
    @image = @gallery.images.new(image_params)

    if @image.save
      redirect_to gallery_path(@gallery)
    else
      render :new 
    end
  end

  def edit
    @gallery = load_gallery_from_url
    @image = @gallery.images.find(params[:id])
  end

  def update
    @gallery = load_gallery_from_url
    @image = @gallery.images.find(params[:id])
    
    if @image.update(image_params)
    redirect_to gallery_image_path(@gallery, @image)
    else
      render :edit
    end
  end

  private
  
  def image_params
    params.require(:image).permit(:name, :url, :tag_words, tag_ids: [], group_ids: [])
  end

  def load_gallery_from_url
    Gallery.find(params[:gallery_id])
  end
end

app/views/images/_form.html.erb
<%= render "error_messages", target: image %>


<%= form_for [gallery, image] do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/images/edit.html.erb
<div>
<h2>You are editing <%= @image.name %></h2>
</div>

<%= render "form", gallery: @gallery, image: @image %>

app/views/images/new.html.erb
<%= render "error_messages", target: @image %>

<%= form_for [@gallery, @image] do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit "Add Image" %>
  </div>

<% end %>

app/views/images/show.html.erb
<h2> You are viewing <%= @image.name %></h2>

<div>
  <%= link_to "Edit Image", edit_gallery_image_path(@gallery, @image) %>
</div>

<%= form_for [@image, @comment] do |form| %>
  <div>
  <%= form.label :body %>
  <%= form.text_area :body %>
</div>

<%= render "error_messages", target: @comment %>

<div>
  <%= form.submit %>
</div>
<% end %>

<% if current_user.likes?(@image) %>
  <%= button_to "Unlike this image", image_like_path(@image), method: :delete %>
<% else %>
  <%= button_to "Like this image", image_like_path(@image) %>
<% end %>

<div>This image has<strong> <%= pluralize @image_like_count, "like" %> </strong></div>

<div>
  <%= form_for [@gallery, @image] do |form| %>
    <%= form.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
  <%= form.submit"Add to groups" %>
<% end %>
</div>

<ul>
  <% @image_likes.each do |like| %>
    <li><%= like.user.email %></li>
<% end %>
</ul>

<p><%= @number_of_tags %></p>

<div>
  <%= form_for [@image.gallery, @image ] do |form| %>
    <%= form.text_field :tag_words %>
  <%= form.submit "Update Tags" %>
<% end %>
</div>


<div>
  <% @comments.recent.word.each do |comment| %>
    <%= render "comments/comment", comment: comment %>
<% end %>
</div>

<%= image_tag @image.url %>